spring:
  datasource:
    username: root
    password: 1
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/cwd_db?
      serverTimezone=UTC&
      useUnicode=true&
      characterEncoding=utf-8&
      useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
mybatis:
  type-aliases-package: com.example.springboot01.pojo

